# Generated by Django 5.2.4 on 2025-10-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('team', 'Team')], max_length=20),
        ),
    ]
